//! Shared plumbing for Flight Deck's native notifications (meeting reminders, new mail): the sounds
//! picked in Settings, and the in-app feed behind the TopBar bell. Each notification is shown by
//! GNOME as a transient popup (so it doesn't pile up in GNOME's list) and also kept in the feed,
//! labelled Email or Meeting, until it's dismissed there.

use notify_rust::{Hint, Notification, Timeout};
use serde::Serialize;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};
use tauri::{AppHandle, Emitter, Manager};

/// Bundled sounds, generated by scripts/gen-sounds.py (all synthesized): id → Ogg file.
const SOUNDS: [(&str, &[u8]); 3] = [
    ("chime", include_bytes!("../sounds/chime.oga")),
    ("blip", include_bytes!("../sounds/blip.oga")),
    ("bell", include_bytes!("../sounds/bell.oga")),
];
/// Meeting reminders.
pub const DEFAULT_SOUND: &str = "bell";
/// New mail.
pub const DEFAULT_MAIL_SOUND: &str = "chime";

pub fn is_known_sound(id: &str) -> bool {
    SOUNDS.iter().any(|(k, _)| *k == id)
}

/// GNOME plays a `sound-file` hint from a path, so the bundled files are written out once per
/// run (rewritten only when they changed).
fn sounds_dir(app: &AppHandle) -> Option<&'static PathBuf> {
    static DIR: OnceLock<Option<PathBuf>> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = app.path().app_data_dir().ok()?.join("sounds");
        std::fs::create_dir_all(&dir).ok()?;
        for (id, bytes) in SOUNDS {
            let path = dir.join(format!("{id}.oga"));
            if !std::fs::read(&path).is_ok_and(|b| b == bytes) {
                std::fs::write(&path, bytes).ok()?;
            }
        }
        for old in ["fly.wav", "fly.oga", "fly1.oga", "fly2.oga", "fly3.oga", "fly4.oga"] {
            let _ = std::fs::remove_file(dir.join(old)); // retired fly sounds
        }
        Some(dir)
    })
    .as_ref()
}

/// Adds the given sound (a Settings id) to the notification; unknown ids get the default.
pub fn set_sound(app: &AppHandle, n: &mut Notification, sound: &str) {
    let id = if is_known_sound(sound) { sound } else { DEFAULT_SOUND };
    if let Some(dir) = sounds_dir(app) {
        n.hint(Hint::SoundFile(dir.join(format!("{id}.oga")).to_string_lossy().into_owned()));
    }
}

/// Most recent feed items kept; older ones drop off.
const FEED_LIMIT: usize = 50;

#[derive(Serialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Kind {
    Email,
    Meeting,
}

#[derive(Serialize, Clone)]
pub struct FeedItem {
    id: u64,
    kind: Kind,
    title: String,
    body: String,
    /// Unix time in milliseconds.
    at: i64,
    /// What clicking it opens: the Outlook conversation id (email) or the join link (meeting).
    target: Option<String>,
}

#[derive(Default)]
struct Feed {
    next_id: u64,
    /// Newest first.
    items: Vec<FeedItem>,
    /// Feed id → GNOME notification id, while the popup is still up.
    native: HashMap<u64, u32>,
}

fn feed() -> &'static Mutex<Feed> {
    static FEED: OnceLock<Mutex<Feed>> = OnceLock::new();
    FEED.get_or_init(Default::default)
}

fn emit_feed(app: &AppHandle) {
    let items = feed().lock().unwrap().items.clone();
    let _ = app.emit_to("main", "notification-feed", items);
}

/// Shows `n` (the caller sets timeout, actions and sound) as a `kind` notification and adds it to
/// the feed. `on_action` gets the clicked action; waiting for it blocks, so it runs on its own
/// thread.
pub fn notify(
    app: &AppHandle,
    kind: Kind,
    title: &str,
    body: &str,
    target: Option<String>,
    mut n: Notification,
    on_action: impl FnOnce(&str) + Send + 'static,
) {
    let (icon, category) = match kind {
        Kind::Email => ("mail-unread", "email.arrived"),
        Kind::Meeting => ("appointment-soon", "x-flight-deck.meeting"),
    };
    n.appname("Flight Deck")
        .summary(title)
        .body(body)
        .icon(icon)
        .hint(Hint::Category(category.into()))
        .hint(Hint::Transient(true));

    let id = {
        let mut f = feed().lock().unwrap();
        f.next_id += 1;
        let id = f.next_id;
        f.items.insert(
            0,
            FeedItem {
                id,
                kind,
                title: title.into(),
                body: body.into(),
                at: chrono::Utc::now().timestamp_millis(),
                target,
            },
        );
        f.items.truncate(FEED_LIMIT);
        id
    };
    emit_feed(app);

    std::thread::spawn(move || {
        let handle = match n.show() {
            Ok(h) => h,
            Err(e) => return eprintln!("notification failed: {e}"),
        };
        #[cfg(all(unix, not(target_os = "macos")))]
        {
            feed().lock().unwrap().native.insert(id, handle.id());
            // Returns on a click and also when the popup is closed.
            handle.wait_for_action(on_action);
            feed().lock().unwrap().native.remove(&id);
        }
        #[cfg(not(all(unix, not(target_os = "macos"))))]
        let _ = (handle, on_action, id);
    });
}

/// Closes GNOME popups that are still up.
async fn close_native(ids: Vec<u32>) -> Result<(), String> {
    if ids.is_empty() {
        return Ok(());
    }
    tauri::async_runtime::spawn_blocking(move || {
        let conn = zbus::blocking::Connection::session().map_err(|e| e.to_string())?;
        for id in ids {
            let _ = conn.call_method(
                Some("org.freedesktop.Notifications"),
                "/org/freedesktop/Notifications",
                Some("org.freedesktop.Notifications"),
                "CloseNotification",
                &(id,),
            );
        }
        Ok(())
    })
    .await
    .map_err(|e| e.to_string())?
}

#[tauri::command]
pub async fn get_notification_feed() -> Result<Vec<FeedItem>, String> {
    Ok(feed().lock().unwrap().items.clone())
}

/// Removes one item from the feed (the × in the bell panel), closing its popup if it is still up.
#[tauri::command]
pub async fn dismiss_notification(app: AppHandle, id: u64) -> Result<(), String> {
    let native = {
        let mut f = feed().lock().unwrap();
        f.items.retain(|i| i.id != id);
        f.native.remove(&id)
    };
    emit_feed(&app);
    close_native(native.into_iter().collect()).await
}

/// Empties the feed and closes any popups still up. Returns how many items were cleared.
#[tauri::command]
pub async fn clear_notifications(app: AppHandle) -> Result<usize, String> {
    let (count, native) = {
        let mut f = feed().lock().unwrap();
        let count = f.items.len();
        f.items.clear();
        (count, f.native.drain().map(|(_, n)| n).collect())
    };
    emit_feed(&app);
    close_native(native).await?;
    Ok(count)
}

/// Picking a sound in Settings plays it in a notification (not added to the feed).
#[tauri::command]
pub async fn preview_notification_sound(app: AppHandle, sound: String) -> Result<(), String> {
    let mut n = Notification::new();
    n.appname("Flight Deck")
        .summary("Sound preview")
        .body("This is how Flight Deck notifications will sound.")
        .icon("flight-deck")
        .timeout(Timeout::Milliseconds(4_000))
        .hint(Hint::Transient(true));
    set_sound(&app, &mut n, &sound);
    std::thread::spawn(move || {
        if let Err(e) = n.show() {
            eprintln!("notification failed: {e}");
        }
    });
    Ok(())
}
